import { createClient } from "@/lib/supabase/client";

export interface GalleryItem {
  id: string;
  url: string;
  imageUrls?: string[];
  mediaType: "image" | "video";
  prompt?: string;
  model?: string;
  aspect_ratio?: string;
  quality?: string;
  azure_resolution?: string;
  source: "generation" | "upload";
  created_at: string;
  referenceImageUrls?: string[];
}

const THUMB_WIDTHS = [16, 32, 48, 64, 96, 128, 256, 384, 640, 750, 828, 1080, 1200, 1920, 2048, 3840];

/**
 * Normalizes assets generated by this app to the origin currently serving it.
 *
 * Local-mode records may contain an old localhost, ngrok, or custom-domain URL.
 * The stored `/generated/...` path identifies an app-owned file, so preserve the
 * path but use the current origin; provider and third-party URLs stay unchanged.
 */
export function assetSrc(url: string): string {
  if (!url || url.startsWith("blob:") || url.startsWith("data:") || url.startsWith("/generated/")) return url;
  try {
    const parsed = new URL(url);
    return parsed.pathname.startsWith("/generated/")
      ? `${parsed.pathname}${parsed.search}${parsed.hash}`
      : url;
  } catch {
    return url;
  }
}

/**
 * Returns a browser-safe thumbnail URL.
 *
 * Only our R2 assets use the server-side thumbnail route. Every other image is
 * loaded by the browser directly: that supports localhost, ngrok, custom
 * domains, signed provider URLs, and future storage hosts without making the
 * image optimizer an allow-list bottleneck.
 */
export function thumbSrc(url: string, w = 96): string {
  const src = assetSrc(url);
  if (!src || src.startsWith("blob:") || src.startsWith("data:")) return src;

  if (src.includes(".r2.dev/")) {
    const target = w * 2;
    const snapped = THUMB_WIDTHS.find((size) => size >= target) ?? THUMB_WIDTHS[THUMB_WIDTHS.length - 1];
    return `/api/thumb?url=${encodeURIComponent(src)}&w=${snapped}`;
  }

  return src;
}

export async function getToken(): Promise<string | undefined> {
  if (process.env.NEXT_PUBLIC_GUEST_MODE === "true") return "guest";
  const { data } = await createClient().auth.getSession();
  return data.session?.access_token;
}

const _galleryCacheMem = new Map<string, { items: GalleryItem[]; hasMore: boolean }>();

export const galleryCache = {
  get(tab: string): { items: GalleryItem[]; hasMore: boolean } | undefined {
    const mem = _galleryCacheMem.get(tab);
    if (mem) return mem;
    try {
      const raw = typeof window !== "undefined" ? localStorage.getItem(`nf-gallery-cache-${tab}`) : null;
      if (!raw) return undefined;
      const parsed = JSON.parse(raw) as { items: GalleryItem[]; hasMore: boolean };
      _galleryCacheMem.set(tab, parsed);
      return parsed;
    } catch { return undefined; }
  },
  set(tab: string, data: { items: GalleryItem[]; hasMore: boolean }) {
    _galleryCacheMem.set(tab, data);
    try {
      if (typeof window !== "undefined") localStorage.setItem(`nf-gallery-cache-${tab}`, JSON.stringify(data));
    } catch { }
  },
};
